### ISSUE TITLE
Lenker og bilde 

### ISSUE THREAD

**Issue by pernillestephensen** [2anmt/Eksamen#8]
Linkene blir stygge når man skalerer ned, skal prøve å fikse men kom gjerne med tips hehe. Også fant jeg ingen bedre måte å senterere bildet på enn å da det i en boks, men vil jo ikke ha border rundt den så vet ikke hvordan jeg skal ordne det. Finnes sikkert bedre måter å gjøre det på men hjernen har kortslutta for dagen

**Comment by 2anmt** [comment]
kan alltids bare fjerne borderen :^)
